version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile  # The Dockerfile for your Django app
    command: gunicorn cardano_cart.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/cardano_cart  # Ensure this points to your actual Django app folder
      - ./static:/app/static  # Volume for static files
      - ./media:/app/media  # Volume for media files
    expose:
      - 8000

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx  # The Dockerfile for Nginx
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./static:/app/static  # Ensure static files are properly mapped
      - ./media:/app/media  # Volume for media files
